# Generated by Django 5.2.7 on 2025-10-31 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('platform_configs', models.JSONField(default=dict, help_text='Configuration spécifique par plateforme (crop, filtres, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='platform_configs',
            field=models.JSONField(default=dict, help_text='Configuration spécifique par plateforme'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Titre optionnel pour organiser les posts', max_length=200),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform_config',
            field=models.JSONField(default=dict, help_text='Configuration spécifique à la plateforme'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Contenu principal du post', validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifié'), ('publishing', 'En cours de publication'), ('published', 'Publié'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook_page', 'Facebook Page'), ('facebook_group', 'Facebook Groupe'), ('instagram_feed', 'Instagram Feed'), ('instagram_story', 'Instagram Story'), ('instagram_reels', 'Instagram Reels'), ('twitter_post', 'Twitter/X Post'), ('linkedin_personal', 'LinkedIn Personnel'), ('linkedin_company', 'LinkedIn Entreprise'), ('tiktok_post', 'TikTok Post'), ('youtube_short', 'YouTube Short')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'platform'], name='scheduler_s_user_id_331ced_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['is_active'], name='scheduler_s_is_acti_cd13fd_idx'),
        ),
        migrations.AddField(
            model_name='postmediaasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_usages', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='postmediaasset',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media_assets', to='scheduler.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_assets',
            field=models.ManyToManyField(blank=True, help_text='Assets média liés à ce post', related_name='linked_posts', through='scheduler.PostMediaAsset', to='media.mediaasset'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'status'], name='scheduler_p_user_id_f6d0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['scheduled_time'], name='scheduler_p_schedul_266dac_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='scheduler_p_created_7878dd_idx'),
        ),
        migrations.AddIndex(
            model_name='postmediaasset',
            index=models.Index(fields=['post', 'order'], name='scheduler_p_post_id_a63684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postmediaasset',
            unique_together={('post', 'asset')},
        ),
    ]
