# Generated by Django 5.2.7 on 2025-10-31 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_postmediaasset_post_is_active_post_platform_configs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform_post_id',
            field=models.CharField(blank=True, help_text='ID du post sur la plateforme après publication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='social_account',
            field=models.ForeignKey(blank=True, help_text='Compte social cible pour la publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.socialaccount'),
        ),
    ]
