# Generated by Django 5.2.7 on 2025-10-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_post_platform_post_id_post_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social_account',
            field=models.ForeignKey(help_text='Compte social cible pour la publication', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scheduler.socialaccount'),
        ),
    ]
