# Generated by Django 5.2.7 on 2025-10-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_post_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='scheduler.socialaccount'),
        ),
    ]
